import "~/styles/globals.css";
import {ClerkProvider} from '@clerk/nextjs'

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by loyal subscriber to theo on youtube", 
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${geist.variable} flex flex-col gap-4`}>

          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
